# Generated by Django 5.2.8 on 2025-11-21 22:47

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='Unique_lower_name_tagname')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the main content text', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Enter content', max_length=500, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date of creation', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date update', verbose_name='Updated')),
                ('author', models.ForeignKey(help_text='Name of the author', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select a tag for this entry', related_name='entries', to='diary.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='diary_entry_created_3f04fb_idx'), models.Index(fields=['author', '-created'], name='diary_entry_author__cd0d28_idx')],
            },
        ),
    ]
