# Generated by Django 5.2.8 on 2025-11-10 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the main content text', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Enter content', max_length=500, verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date of creation', verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date update', verbose_name='Updated')),
                ('author', models.ForeignKey(help_text='Name of the author', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select a tag for this entry', related_name='entries', to='diary.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='diary_entry_created_ca7a2e_idx'), models.Index(fields=['author', '-created_at'], name='diary_entry_author__05d4cc_idx')],
            },
        ),
    ]
